### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by rahulkapoor90**

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
Why "close" the pull request without mentioning the problem?

**Comment by kashishbest** [comment]
Hey Rahul,

Sorry for the inconvenience. Our member was a little over enthusiastic, and I apologise for not paying attention to this earlier. Your and everybody else's contributions are most welcome.

**Comment by aneesh-neelam** [comment]
Hey, what is this project anyway?

**Comment by rahulkapoor90** [comment]
@kashishbest i appreciate that.

**Comment by kashishbest** [comment]
I dont know why Kunal used motherload, but as far as I know, it is a project, to build stuff for gravitas
1. website, 
2. registration portals. 
I may be mistaken

**Pull request merged**
